name: Build and Publish Docker

on:
  push:
    branches:
      - master
      - develop
  schedule:
    - cron:  '5 5 */7 * *'

jobs:
  update_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install xmllint
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils
      - name : update lists
        shell: bash
        run : |
          bash update-known-public-dns.sh
          date -I > last-update.txt
          date -I >> update.txt
      - name: push updated lists
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update-lists
